[server]
headless = true
address = "0.0.0.0"
port = 5000

[theme]
primaryColor = "#2563EB"
backgroundColor = "#F9F9FE"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "sans serif"

[deprecation]
showPyplotGlobalUse = false
